services:
  inferno-comics-web:
    image: infernokun/inferno-comics-web:latest
    #build: ./inferno-comics-web
    restart: always
    environment:
      - BASE_URL=http://inferno-comics-web
      - REST_URL=/api
    ports:
      - "8784:80"
    volumes:
      - inferno-comics-web:/var/log/nginx
    networks:
      - inferno-comics-network

  inferno-comics-db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-inferno-comics}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-inferno-comics}"
      POSTGRES_DB: "${POSTGRES_DB:-inferno-comics}"
    volumes:
      - inferno-comics-db:/var/lib/postgresql/data
    networks:
      - inferno-comics-network

  inferno-comics-rest:
    image: infernokun/inferno-comics-rest:latest
    #build: ./inferno-comics-rest
    restart: always
    ports:
      - "8785:8080"
    environment:
      DOCKER_COMPOSE_PATH: "${DOCKER_COMPOSE_PATH:-/var/tmp/inferno-comics}"
      DB_IP: "${POSTGRES_IP:-inferno-comics-db}"
      DB_NAME: "${POSTGRES_DB:-inferno-comics}"
      DB_USER: "${POSTGRES_USER:-inferno-comics}"
      DB_PASS: "${POSTGRES_PASSWORD:-inferno-comics}"
      DB_PORT: "${DB_PORT:-5432}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY:-secret_key}"
      RSA_PRIVATE_KEY_PATH: "${RSA_PRIVATE_KEY_PATH:-/var/tmp/inferno-comics/private.pem}"
      RSA_PUBLIC_KEY_PATH: "${RSA_PUBLIC_KEY_PATH:-/var/tmp/inferno-comics/public.pem}"
      REDIS_HOST: "${REDIS_HOST:-inferno-comics-redis}"
      REDIS_PORT: "${REDIS_PORT:-6379}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-inferno-comics}"
      COMIC_VINE_API_KEY: "${COMIC_VINE_API_KEY}"
      GROQ_API_KEY: "${GROQ_API_KEY}"
    volumes:
      - /var/tmp/inferno-comics:/var/tmp/inferno-comics
    networks:
      - inferno-comics-network

  inferno-comics-redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - inferno-comics-redis:/data
    networks:
      - inferno-comics-network
    environment:
      - REDIS_PASSWORD=inferno-comics
    command: redis-server --appendonly yes --requirepass inferno-comics

networks:
  inferno-comics-network:
    driver: bridge
    name: inferno-comics-network

volumes:
  inferno-comics-db:
    driver: local
  inferno-comics-redis:
    driver: local
  inferno-comics-web:
    driver: local