services:
  postgres:
    image: postgres:17.4
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-inferno-comics}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-inferno-comics}
      POSTGRES_DB: ${POSTGRES_DB:-inferno-comics}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inferno-comics-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER:-inferno-comics}@${POSTGRES_USER:-inferno-comics}.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-inferno-comics}
    ports:
      - "5050:80"
    networks:
      - inferno-comics-network

volumes:
  postgres-data:

networks:
  inferno-comics-network:
    driver: bridge
