# Comic Matcher Configuration - Optimized for AKAZE Performance
# Hardware Performance Level (overrides individual settings below)
# Options: "minimal", "fast", "balanced", "high_performance"
performance_level: "balanced"
result_batch: 10
simularity_threshold: 55%

# Performance Presets - Optimized for Processing Power vs Accuracy
presets:
  minimal:  # For very slow hardware - ORB only for speed
    image_size: 300
    max_workers: 1
    detectors:
      sift: 0        # Disable - too slow
      orb: 500       # Fast and reasonable
      akaze: 0       # Disable - save processing
      kaze: 0        # Disable - too slow
    feature_weights:
      sift: 0.0
      orb: 1.0       # 100% ORB for speed
      akaze: 0.0
      kaze: 0.0
    options:
      use_comic_detection: false
      use_advanced_matching: false
      cache_only: true
      
  fast:  # For decent hardware - optimized for speed with good accuracy
    image_size: 800
    max_workers: 3
    detectors:
      sift: 800        # Include SIFT for better matching
      orb: 1200        # High ORB for speed
      akaze: 600       # Good AKAZE for accuracy
      kaze: 0          # Skip KAZE for speed
    feature_weights:
      sift: 0.25       # 25% SIFT for quality
      orb: 0.35        # 35% ORB for speed
      akaze: 0.40      # 40% AKAZE for accuracy
      kaze: 0.0
    options:
      use_comic_detection: true     # Enable for better accuracy
      use_advanced_matching: true   # Keep advanced matching for quality
      
  balanced:  # AKAZE-focused with SIFT/ORB support
    image_size: 1000
    max_workers: 4
    detectors:
      sift: 1500     # Moderate SIFT
      orb: 1500      # Good ORB count
      akaze: 800     # High AKAZE - our star performer
      kaze: 400      # Moderate KAZE
    feature_weights:
      sift: 0.20     # 20% SIFT
      orb: 0.20      # 20% ORB  
      akaze: 0.50    # 50% AKAZE - most accurate
      kaze: 0.10     # 10% KAZE
    options:
      use_comic_detection: true
      use_advanced_matching: true
      
  high_performance:  # Maximum accuracy - all detectors optimized
    image_size: 1200
    max_workers: 8
    detectors:
      sift: 2500     # Maximum SIFT
      orb: 2000      # High ORB
      akaze: 1200    # Maximum AKAZE features
      kaze: 800      # High KAZE
    feature_weights:
      sift: 0.25     # 25% SIFT
      orb: 0.20      # 20% ORB
      akaze: 0.45    # 45% AKAZE - still dominant
      kaze: 0.10     # 10% KAZE
    options:
      use_comic_detection: true
      use_advanced_matching: true
      
  akaze_focused:  # Custom preset - AKAZE-dominant for maximum accuracy
    image_size: 800
    max_workers: 4
    detectors:
      sift: 800
      orb: 800
      akaze: 1000    # Maximize AKAZE
      kaze: 200
    feature_weights:
      sift: 0.15     # 15% SIFT
      orb: 0.15      # 15% ORB
      akaze: 0.65    # 65% AKAZE - maximum accuracy
      kaze: 0.05     # 5% KAZE
    options:
      use_comic_detection: true
      use_advanced_matching: true