management:
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST,PUT,OPTIONS,DELETE
        allowed-origins: '"*"'
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      livenessState:
        enabled: true
      readinessState:
        enabled: true
  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/${DB_NAME:inferno-comics}
    username: ${DB_USER:inferno-comics}
    password: ${DB_PASS:inferno-comics}
  jpa:
    hibernate:
      ddl-auto: update 
    open-in-view: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:inferno-comics}
    timeout: 6000
    database: 0

  jackson:
    default-property-inclusion: NON_NULL
server:
  forward-headers-strategy: native
  port: 8080
  servlet:
    contextPath: /inferno-comics-rest
  shutdown: graceful
  tomcat:
    internal-proxies:
      protocol-header: "X-Forwarded-Proto"
      remote-ip-header: "X-FORWARDED-FOR"
  use-forward-headers: true

inferno-comics:
  applicationName: "InfernoComics"
  defaultAdminUsername: inferno-comics_admin
  defaultAdminPassword: password
  encryptionKey: "${ENCRYPTION_KEY}"
  comicVineAPIKey: "${COMIC_VINE_API_KEY}"
  groqAPIKey: "${GROQ_API_KEY}"
  groqModel: "llama-3.1-8b-instant"

logging:
  level:
    org.hibernate: WARN
    org.hibernate.orm.connections.pooling: ERROR

rsa:
  private-key: ${RSA_PRIVATE_KEY_PATH:certs/private.pem}
  public-key: ${RSA_PUBLIC_KEY_PATH:certs/public.pem}